name = "x402-multichain-verifier"
main = "src/index.ts"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]
account_id = "6a10ee79fe9d21b5e2c3155ce8690742"

[vars]
BASE_USDC_ADDRESS = "0x036CbD53842c5426634e7929541eC2318f3dCF7e"
BASE_NETWORK = "eip155:84532"
SOL_USDC_MINT = "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU"
SOL_NETWORK = "solana:EtWTRABZaYq6iMfeYKouRu166VU2xqa1"
