name = "sui-ski-lift"
main = "../src/index.ts"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]
account_id = "6a10ee79fe9d21b5e2c3155ce8690742"

routes = [
  { pattern = "lift.sui.ski/*", zone_name = "sui.ski" }
]

[vars]
SUI_NETWORK = "mainnet"
WALRUS_NETWORK = "mainnet"
SEAL_NETWORK = "testnet"
SEAL_PACKAGE_ID = "0x8afa5d31dbaa0a8fb07082692940ca3d56b5e856c5126cb5a3693f0a4de63b82"
SEAL_KEY_SERVERS = "0x73d05d62c18d9374e3ea529e8e0ed6161da1a141a94d3f76ae3fe4e99356db75,0xf5d14a81a982144ae441cd7d64b09027f116a468bd36e7eca494f750591623c8,0x4cded1abeb52a22b6becb42a91d3686a4c901cf52eee16234214d0b5b2da4c46"
SKI_OPERATOR = "brando.sui"
SKI_FACILITATOR = "extra.sui"
DECAY_AUCTION_PACKAGE_ID = "0x10dbff33383bdb68d0bbf6aadeed5e2d3911c45b03664130ebb16437954a2f40"

[[kv_namespaces]]
binding = "CACHE"
id = "c0054cf22c6a4daa99cb36347fa5229c"

[[durable_objects.bindings]]
name = "WALLET_SESSIONS"
class_name = "WalletSession"
script_name = "sui-ski-gateway"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WalletSession"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["SuiPayAgent", "SuiMcpServer"]

[[migrations]]
tag = "v3"
deleted_classes = ["SuiPayAgent", "SuiMcpServer"]
